vpc_cidr: 10.4.0.0/16
vpc_subnets:
  private-1:
    cidr: 10.4.1.0/24
    az: "{{ aws_region }}b"
  private-2:
    cidr: 10.4.2.0/24
    az: "{{ aws_region }}c"
  private-3:
    cidr: 10.4.3.0/24
    az: "{{ aws_region }}d"