---
- name: Gather instance facts
  ec2_instance_facts:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      "tag:app": "{{ instance }}"
      instance-state-name: "running"
  register: existing_ec2_instances
- debug: msg="instance id {{ existing_ec2_instances.instances.0.instance_id }}"

- name: Remove all tags except Name from an instance
  amazon.aws.ec2_tag:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    resource: "{{ existing_ec2_instances.instances.0.instance_id }}"
    tags:
      Name: ''
    state: absent
    purge_tags: true

- name: Terminate instance
  ec2:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    state: absent
    instance_id: "{{ existing_ec2_instances.instances.0.instance_id }}"
    wait: true

- name: Disassociate EIP to instance
  ec2_eip:
    profile: "{{ aws_profile}}"
    region: "{{ aws_region }}"
    device_id: "{{ existing_ec2_instances.instances.0.instance_id }}"
    in_vpc: yes
    state: absent
    public_ip: "{{ EIP }}"
    release_on_disassociation: no

- name: Retrieve A record with specified EIP
  route53:
    profile: "{{ aws_profile}}"
    state: get
    zone: "{{ aws_hosted_zone }}"
    record: "{{ aws_dns_record }}"
    type: A
  register: rec

- name: Delete A record with specified EIP
  route53:
    profile: "{{ aws_profile}}"
    state: absent
    zone: "{{ aws_hosted_zone }}"
    record: "{{ rec.set.record }}"
    ttl: "{{ rec.set.ttl }}"
    type: "{{ rec.set.type }}"
    value: "{{ rec.set.value }}"