---
- name: Gather Jenkins instance facts
  ec2_instance_facts:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      "{{ input_filters }}"
  register: jenkins_existing_ec2_instances
- debug: msg="instance id {{ jenkins_existing_ec2_instances.instances.0.instance_id }}"

- name: Remove all tags except Name from an instance
  amazon.aws.ec2_tag:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    resource: "{{ jenkins_existing_ec2_instances.instances.0.instance_id }}"
    tags:
      Name: ''
    state: absent
    purge_tags: true

- name: Terminate Jenkins instance
  ec2:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    state: absent
    instance_id: "{{ jenkins_existing_ec2_instances.instances.0.instance_id }}"
    wait: true

- name: Disassociate EIP to Jenkins instance
  ec2_eip:
    profile: "{{ aws_profile}}"
    region: "{{ aws_region }}"
    device_id: "{{ jenkins_existing_ec2_instances.instances.0.instance_id }}"
    in_vpc: yes
    state: absent
    public_ip: "{{ EIP }}"
    release_on_disassociation: no