---
- name: Update an A record with specified EIP
  community.aws.route53:
    profile: "{{ aws_profile }}"
    state: present
    overwrite: yes
    zone: "{{ aws_hosted_zone }}"
    record: "{{ aws_dns_record }}"
    type: A
    ttl: "{{ ttl }}"
    value: 
      - "{{ EIP }}"
    wait: yes
