---
- name: Create namespace
  shell: kubectl create ns monitoring

- name: Install monitoring stack
  shell: |
    helm dependency update /Users/martin/go/src/acc/helm-chart-metrics/metrics
    helm install prometheus /Users/martin/go/src/acc/helm-chart-metrics/metrics
