---
- name: Get vpc peering facts
  ec2_vpc_peering_facts:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": k8s_rds
  register: vpc_peer_facts
  
- name: Set vpc peering facts
  set_fact:
    peering_id: "{{ vpc_peer_facts.result.0.vpc_peering_connection_id }}"

- name: Delete vpc peering
  ec2_vpc_peer:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    peering_id: "{{ peering_id }}"
    state: absent
  register: delete_vpc_peer

- name: Terminate rds instance
  rds:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    command: delete
    instance_name: "{{ rds_instance_name }}"
    wait: yes
    wait_timeout: 600

- name: get vpc facts
  ec2_vpc_net_facts:
    profile: "{{ aws_profile}}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ sg_vpc_name }}"
  register: rds_vpc_facts

- name: set vpc facts
  set_fact:
    rds_vpc_id: "{{ rds_vpc_facts.vpcs.0.vpc_id }}"
- debug: var=rds_vpc_id

- name: Delete rds security group
  ec2_group:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ rds_vpc_id }}"
    name: "rds_sg_{{ rds_vpc_id }}"
    state: absent
