---
    - name: "Delete k8s cluster"
      hosts: localhost
      gather_facts: yes
      roles:
        #- delete-elasticsearch
        #- delete-kafka
        #- delete-rds
        - delete-k8s-cluster