---
    - name: "Setup k8s cluster"
      hosts: localhost
      gather_facts: yes
      roles:
        - setup-k8s-cluster
        - setup-rds
        - setup-rdsbest
        - setup-rdsnew
        - setup-rdstop
        - setup-kafka
        - setup-elasticsearch