---
    - name: "Setup k8s cluster"
      hosts: localhost
      gather_facts: yes
      roles:
        - setup-k8s-cluster
        - setup-k8s-metrics-server
        - setup-k8s-efk
        - setup-k8s-monitoring
        - setup-rds
        - setup-kafka
        - setup-elasticsearch