apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: k8s.prod.bh7cw.me
    http:
      paths:
      - path: /webapp
        pathType: Prefix
        backend:
          service:
            name: webapp-deployment-svc
            port:
              number: 8080
      - path: /best
        pathType: Prefix
        backend:
          service:
            name: processor-webapp-best-deployment-svc
            port:
              number: 80
      - path: /new
        pathType: Prefix
        backend:
          service:
            name: processor-webapp-new-deployment-svc
            port:
              number: 80
      - path: /top
        pathType: Prefix
        backend:
          service:
            name: processor-webapp-top-deployment-svc
            port:
              number: 80
      - path: /notifier
        pathType: Prefix
        backend:
          service:
            name: notifier-webapp-deployment-svc
            port:
              number: 80
  tls:
  - secretName: webapp-tls-cert
    hosts:
      - k8s.prod.bh7cw.me