apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: k8s.prod.bh7cw.me
    http:
      paths:
      - backend:
          serviceName: webapp-deployment-svc
          servicePort: 8080
        path: /
  - host: best.processor.k8s.prod.bh7cw.me
    http:
      paths:
      - backend:
          serviceName: processor-webapp-best-deployment-svc
          servicePort: 80
        path: /
  - host: new.processor.k8s.prod.bh7cw.me
    http:
      paths:
      - backend:
          serviceName: processor-webapp-new-deployment-svc
          servicePort: 80
        path: /
  - host: top.processor.k8s.prod.bh7cw.me
    http:
      paths:
      - backend:
          serviceName: processor-webapp-top-deployment-svc
          servicePort: 80
        path: /
  - host: notifier.k8s.prod.bh7cw.me
    http:
      paths:
      - backend:
          serviceName: notifier-webapp-deployment-svc
          servicePort: 80
        path: /
  tls:
  - secretName: webapp-tls-cert
    hosts:
      - k8s.prod.bh7cw.me
      - best.processor.k8s.prod.bh7cw.me
      - new.processor.k8s.prod.bh7cw.me
      - top.processor.k8s.prod.bh7cw.me
      - notifier.k8s.prod.bh7cw.me