---
- name: Get vpc peering facts
  ec2_vpc_peering_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": Peering connection for k8s and rds
  register: vpc_peer_facts
  
- name: Set vpc peering facts
  set_fact:
    peering_id: "{{ vpc_peer_facts.result.0.peering_id }}"

- name: Delete vpc peering
  ec2_vpc_peer:
    peering_id: "{{ peering_id }}"
    state: absent
  register: delete_vpc_peer

- name: Terminate rds instance
  rds:
    command: delete
    instance_name: rds

- name: delete rds security group
  ec2_group:
    vpc_id: "{{ rds_vpc_id }}"
    name: "rds_sg_{{ rds_vpc_id }}"
    state: absent

- name: Delete cluster
  shell: kops delete cluster --name "{{ k8s_domain_name }}" --state=s3://"{{ k8s_domain_name }}" --yes