---
aws_region: us-east-1
aws_profile: prod
service_name: rds
rds_username: springuser
rds_password: thepassword

rds_instance_name: my-instance

sg_vpc_name: "{{ service_name }}-{{ aws_region }}-vpc"
subnet_name: "{{ service_name }}_{{ aws_region }}b"
k8s_vpc_name: "{{ k8s_domain_name }}"