---
- name: Set up kafka cluster
  shell: |
    helm repo add bitnami https://charts.bitnami.com/bitnami
    helm install kafka -f kafka/values.yaml bitnami/kafka --wait

- name: Verify Kafka topics
  shell: |
    kubectl run kafka-client --restart='Never' --image docker.io/bitnami/kafka:2.7.0-debian-10-r64 --namespace default --command -- sleep infinity
    sleep 30
    kubectl exec -i kafka-client --namespace default -- kafka-topics.sh --list --bootstrap-server kafka.default.svc.cluster.local:9092