---
- name: Gather information about all availability zones
  aws_az_info:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
  register: az

- debug: var=az.availability_zones

- name: get k8s vpc cidr
  ec2_vpc_net_facts:
    profile: "{{ aws_profile}}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ k8s_vpc_name }}"
  register: k8s_vpc_facts

- name: set k8s vpc facts
  set_fact:
    k8s_vpc_cidr: "{{ k8s_vpc_facts.vpcs.0.cidr_block }}"
    k8s_vpc_id: "{{ k8s_vpc_facts.vpcs.0.vpc_id }}"
- debug: var=k8s_vpc_cidr

- name: Grab the k8s route tables
  ec2_vpc_route_table_info:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ k8s_vpc_id }}"
      "tag:Name": "{{ k8s_vpc_name }}"
  register: k8s_route_table

  - name: Get k8s igw info
  ec2_vpc_igw_info:
    profile: "{{ aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ k8s_vpc_name }}"
      attachment.vpc-id: "{{ k8s_vpc_id }}"
  register: k8s_igw